
["Configs for Paintable"]
	#Paint every colored block that has unique design/texture, like Doors, Trapdoors, Glazed Terracotta
	#Default: false
	can_paint = false
	#The amount of times you can paint blocks using the brush
	#Default: 16
	#Range: 4 ~ 64
	paint_limit = 16

